# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_items_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.ImageField(default='null', upload_to='myitems/'),
        ),
    ]
