# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_items_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image2',
            field=models.ImageField(default='null', help_text='Upload item image 2', upload_to='myitems/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_image',
            field=models.ImageField(default='null', help_text='Upload item image 1', upload_to='myitems/'),
        ),
    ]
