# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20180306_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='n', upload_to='images'),
            preserve_default=False,
        ),
    ]
