# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='exchange_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_category', to='categories.Category'),
        ),
    ]
