# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('categories', '0009_items_exchange_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='bnd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Brand'),
        ),
    ]
