# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_items_cat_bnd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='cat_bnd',
        ),
        migrations.DeleteModel(
            name='CategoryBrand',
        ),
    ]
