# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_auto_20180409_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='other_info',
            field=models.CharField(default='o', help_text='Item other information', max_length=150),
            preserve_default=False,
        ),
    ]
