# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_items_other_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='other_info',
            field=models.CharField(default='null', help_text='Item other information', max_length=150),
        ),
    ]
