# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_auto_20180420_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='months_used',
            field=models.PositiveSmallIntegerField(help_text='No of Months'),
        ),
        migrations.AlterField(
            model_name='items',
            name='years_used',
            field=models.PositiveSmallIntegerField(default=1, help_text='No of Years'),
        ),
    ]
