# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
        ('categories', '0016_auto_20180426_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnd_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Brand')),
                ('cat_nam', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cat_name', to='categories.Category')),
            ],
        ),
    ]
