# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-14 01:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0019_userwhishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwhishlist',
            unique_together=set([('user', 'item')]),
        ),
    ]
