# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0021_uservieweditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('citem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_citems', to='categories.Items')),
                ('myitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_myitems', to='categories.Items')),
                ('ruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
