# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-30 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0022_requesteditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 10, 12, 56, 747135, tzinfo=utc)),
        ),
    ]
