# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0023_items_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
