# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(blank=True, max_length=80, null=True)),
                ('bug_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('NOTSTARTED', 'NOT-STARTED'), ('INPROGRESS', 'IN-PROGRESS'), ('FIXED', 'FIXED')], max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('WEBSITE', 'WEBSITE'), ('MOBILEAPP', 'MOBILEAPP'), ('BUSINESS', 'BUSINESS')], max_length=100, null=True)),
            ],
        ),
    ]
