# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugsreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='document',
            field=models.FileField(default='bugissue/default/no-img.jpg', upload_to='documents/'),
        ),
    ]
