# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfullprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfullprofile',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
