# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180530_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfullprofile',
            name='user_image',
            field=models.ImageField(default='null', help_text='Upload user image', upload_to='user_image/'),
        ),
    ]
